import { Metadata } from "next";
import { EntryType } from "@/lib/mockData";
import { breadCategory } from "@/lib/categoryData";
import ProductList from "../_components/shared/ProductList";
import { IProduct } from "@/models/Product";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const data: IProduct[] = await fetch(
    `http://localhost:3000/api/categories/bread`
  )
    .then((res) => res.json())
    .then((data) => data.data);

  return (
    <ProductList
      category="breads"
      data={data}
      asideCategories={breadCategory}
    />
  );
}

export default page;
