import { Metadata } from "next";
import { breadCategory } from "@/lib/categoryData";
import ProductList from "../_components/shared/ProductList";
import { IProduct } from "@/models/Product";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const res = await fetch(`http://localhost:3000/api/categories/bread`);
  if (!res.ok) {
    const data = await res.json();
    throw new Error(data.error);
  }
  const { data }: { data: IProduct[] } = await res.json();

  return (
    <ProductList
      category="breads"
      data={data}
      asideCategories={breadCategory}
    />
  );
}

export default page;
