import { Metadata } from "next";
import { cakeCategory } from "@/lib/categoryData";
import ProductList from "../_components/shared/ProductList";
import { IProduct } from "@/models/Product";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const data: IProduct[] = await fetch(
    `http://localhost:3000/api/categories/cake`
  )
    .then((res) => res.json())
    .then((data) => data.data);

  return (
    <ProductList category="cakes" data={data} asideCategories={cakeCategory} />
  );
}

export default page;
