import { Metadata } from "next";
import ProductList from "../_components/ProductList";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  return <ProductList category="cakes" />;
}

export default page;
