import { Metadata } from "next";
import ProductList from "../_components/ProductList";
import { EntryType } from "@/lib/mockData";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const data = await fetch(`http://localhost:3000/api/cakes`)
    .then((res) => res.json())
    .then((data) => data.data as EntryType[]);

  return <ProductList category="cakes" data={data} />;
}

export default page;
