export type EntryType = {
  id: number;
  title: string;
  size?: string[];
  description: string;
  price: string[] | string;
  category: string;
};

export const cakes: EntryType[] = [
  {
    id: 1,
    title: "Strawberry Shortcake",
    size: ['7"', '8"'],
    description:
      "Soft sponge layered with fresh strawberries and whipped cream.",
    price: ["29.99", "34.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 2,
    title: "Chocolate Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Rich chocolate mousse layered with airy chocolate sponge.",
    price: ["32.99", "38.99", "42.99"],
    category: "Mousse Cake",
  },
  {
    id: 3,
    title: "Unicorn Cream Cake",
    size: ['7"'],
    description: "Colorful unicorn-themed cake with pastel whipped cream.",
    price: ["45.99"],
    category: "Character Cake",
  },
  {
    id: 4,
    title: "Blueberry Mousse Cake",
    size: ['6"', '8"'],
    description: "Airy blueberry mousse paired with vanilla sponge.",
    price: ["31.99", "37.99"],
    category: "Mousse Cake",
  },
  {
    id: 5,
    title: "Red Velvet Cake",
    size: ['8"'],
    description: "Classic red velvet with rich cream cheese frosting.",
    price: ["42.99"],
    category: "Special Cake",
  },
  {
    id: 6,
    title: "Matcha Slice Cake",
    size: ["Single"],
    description: "Matcha sponge slice with earthy matcha cream.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 7,
    title: "Mango Fresh Cream Cake",
    size: ['6"'],
    description: "Vanilla sponge with fresh mango and cream.",
    price: ["30.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 8,
    title: "Car Race Chocolate Cake",
    size: ['7"', '8"'],
    description: "Race car–inspired chocolate birthday cake.",
    price: ["54.99", "64.99"],
    category: "Character Cake",
  },
  {
    id: 9,
    title: "Tiramisu Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Coffee-soaked sponge with mascarpone mousse.",
    price: ["33.99", "39.99", "42.99"],
    category: "Mousse Cake",
  },
  {
    id: 10,
    title: "Cheesecake Slice",
    size: ["Single"],
    description: "Classic creamy cheesecake slice.",
    price: ["6.99"],
    category: "Slice Cake",
  },
  {
    id: 11,
    title: "Grapes Fresh Cream Cake",
    size: ['7"'],
    description: "Light cream cake topped with seasonal grapes.",
    price: ["35.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 12,
    title: "Milk Tea Mousse Cake",
    size: ['6"', '8"'],
    description: "Smooth milk tea mousse with tea-infused sponge.",
    price: ["32.99", "38.99"],
    category: "Mousse Cake",
  },
  {
    id: 13,
    title: "Dinosaur Chocolate Cake",
    size: ['8"'],
    description: "Fun dinosaur-themed chocolate cake.",
    price: ["54.99"],
    category: "Character Cake",
  },
  {
    id: 14,
    title: "New York Cheesecake",
    size: ['6"', '8"'],
    description: "Dense baked cheesecake with a graham crust.",
    price: ["35.99", "44.99"],
    category: "Special Cake",
  },
  {
    id: 15,
    title: "Vanilla Custard Slice",
    size: ["Single"],
    description: "Soft sponge slice filled with vanilla custard.",
    price: ["5.49"],
    category: "Slice Cake",
  },
  {
    id: 16,
    title: "Blueberry Fresh Cream Cake",
    size: ['6"', '7"', '8"'],
    description: "Fluffy sponge with blueberry compote and cream.",
    price: ["29.99", "34.99", "38.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 17,
    title: "Princess Strawberry Cake",
    size: ['7"'],
    description: "Strawberry cake decorated with princess toppers.",
    price: ["56.99"],
    category: "Character Cake",
  },
  {
    id: 18,
    title: "Chocolate Ganache Cake",
    size: ['6"', '7"', '8"'],
    description: "Deep chocolate sponge covered in silky ganache.",
    price: ["35.99", "40.99", "45.99"],
    category: "Special Cake",
  },
  {
    id: 19,
    title: "Triple Chocolate Cake",
    size: ['8"'],
    description: "Layers of milk, dark, and white chocolate.",
    price: ["45.99"],
    category: "Special Cake",
  },
];
