export type EntryType = {
  id: number;
  title: string;
  size?: string[];
  description: string;
  price: string[] | string;
  category: string;
};

export const cakes: EntryType[] = [
  {
    id: 1,
    title: "Strawberry Shortcake",
    size: ['7"', '8"'],
    description:
      "Soft sponge layered with fresh strawberries and whipped cream.",
    price: ["29.99", "34.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 2,
    title: "Chocolate Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Rich chocolate mousse layered with airy chocolate sponge.",
    price: ["32.99", "38.99"],
    category: "Mousse Cake",
  },
  {
    id: 3,
    title: "Unicorn Cream Cake",
    size: ['7"'],
    description: "Colorful unicorn-themed cake with pastel whipped cream.",
    price: ["45.99"],
    category: "Character Cake",
  },
  {
    id: 4,
    title: "Blueberry Mousse Cake",
    size: ['6"', '8"'],
    description: "Airy blueberry mousse paired with vanilla sponge.",
    price: ["31.99", "37.99"],
    category: "Mousse Cake",
  },
  {
    id: 5,
    title: "Red Velvet Cake",
    size: ['8"'],
    description: "Classic red velvet with rich cream cheese frosting.",
    price: ["42.99"],
    category: "Special Cake",
  },
  {
    id: 6,
    title: "Matcha Slice Cake",
    size: ["Single"],
    description: "Matcha sponge slice with earthy matcha cream.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 7,
    title: "Mango Fresh Cream Cake",
    size: ['6"'],
    description: "Vanilla sponge with fresh mango and cream.",
    price: ["30.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 8,
    title: "Car Race Chocolate Cake",
    size: ['7"', '8"'],
    description: "Race car–inspired chocolate birthday cake.",
    price: ["54.99", "64.99"],
    category: "Character Cake",
  },
  {
    id: 9,
    title: "Tiramisu Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Coffee-soaked sponge with mascarpone mousse.",
    price: ["33.99", "39.99"],
    category: "Mousse Cake",
  },
  {
    id: 10,
    title: "Cheesecake Slice",
    size: ["Single"],
    description: "Classic creamy cheesecake slice.",
    price: ["6.99"],
    category: "Slice Cake",
  },
  {
    id: 11,
    title: "Grapes Fresh Cream Cake",
    size: ['7"'],
    description: "Light cream cake topped with seasonal grapes.",
    price: ["35.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 12,
    title: "Milk Tea Mousse Cake",
    size: ['6"', '8"'],
    description: "Smooth milk tea mousse with tea-infused sponge.",
    price: ["32.99", "38.99"],
    category: "Mousse Cake",
  },
  {
    id: 13,
    title: "Dinosaur Chocolate Cake",
    size: ['8"'],
    description: "Fun dinosaur-themed chocolate cake.",
    price: ["54.99"],
    category: "Character Cake",
  },
  {
    id: 14,
    title: "New York Cheesecake",
    size: ['6"', '8"'],
    description: "Dense baked cheesecake with a graham crust.",
    price: ["35.99", "44.99"],
    category: "Special Cake",
  },
  {
    id: 15,
    title: "Vanilla Custard Slice",
    size: ["Single"],
    description: "Soft sponge slice filled with vanilla custard.",
    price: ["5.49"],
    category: "Slice Cake",
  },
  {
    id: 16,
    title: "Blueberry Fresh Cream Cake",
    size: ['6"', '7"', '8"'],
    description: "Fluffy sponge with blueberry compote and cream.",
    price: ["29.99", "34.99", "38.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 17,
    title: "Princess Strawberry Cake",
    size: ['7"'],
    description: "Strawberry cake decorated with princess toppers.",
    price: ["56.99"],
    category: "Character Cake",
  },
  {
    id: 18,
    title: "Chocolate Ganache Cake",
    size: ['6"', '7"', '8"'],
    description: "Deep chocolate sponge covered in silky ganache.",
    price: ["35.99", "40.99", "45.99"],
    category: "Special Cake",
  },
  {
    id: 19,
    title: "Triple Chocolate Cake",
    size: ['8"'],
    description: "Layers of milk, dark, and white chocolate.",
    price: ["45.99"],
    category: "Special Cake",
  },
  {
    id: 20,
    title: "Strawberry Slice Cake",
    size: ["Single"],
    description: "Vanilla sponge slice topped with fresh strawberries.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 21,
    title: "Vanilla Ice Cream Cake",
    size: ['6"', '8"'],
    description: "Vanilla sponge with ice cream and whipped cream.",
    price: ["28.99", "32.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 22,
    title: "Lemon Cream Cake",
    size: ['7"', '8"'],
    description: "Bright lemon sponge balanced with lemon cream.",
    price: ["33.99", "40.99"],
    category: "Special Cake",
  },
  {
    id: 23,
    title: "Panda Mousse Cake",
    size: ['6"', '7"'],
    description: "Cute panda-themed chocolate mousse cake.",
    price: ["46.99", "52.99"],
    category: "Character Cake",
  },
  {
    id: 24,
    title: "Oreo Cheesecake",
    size: ['6"', '8"'],
    description: "Oreo crust with creamy cheesecake blended with cookies.",
    price: ["36.99", "45.99"],
    category: "Special Cake",
  },
  {
    id: 25,
    title: "Chocolate Fudge Slice",
    size: ["Single"],
    description: "Moist chocolate slice with fudge frosting.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 26,
    title: "Banana Fresh Cream Cake",
    size: ['6"'],
    description: "Vanilla sponge with banana slices and cream.",
    price: ["28.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 27,
    title: "Hazelnut Mousse Cake",
    size: ['7"', '8"'],
    description: "Hazelnut mousse layered with chocolate sponge.",
    price: ["33.99", "40.99"],
    category: "Mousse Cake",
  },
  {
    id: 28,
    title: "Mermaid Cream Cake",
    size: ['8"'],
    description: "Ocean-themed mermaid cake with pastel colors.",
    price: ["55.99"],
    category: "Character Cake",
  },
  {
    id: 29,
    title: "Carrot Cake Slice",
    size: ["Single"],
    description: "Moist carrot cake slice with cream cheese frosting.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 30,
    title: "Raspberry Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Tangy raspberry mousse with soft sponge.",
    price: ["32.99", "37.99", "42.99"],
    category: "Mousse Cake",
  },
  {
    id: 31,
    title: "Bear Fresh Cream Cake",
    size: ['6"', '7"'],
    description: "Cute bear-shaped vanilla cream cake.",
    price: ["45.99", "52.99"],
    category: "Character Cake",
  },
  {
    id: 32,
    title: "Mango Mousse Cake",
    size: ['7"', '8"'],
    description: "Smooth mango mousse layered with soft sponge.",
    price: ["31.99", "38.99"],
    category: "Mousse Cake",
  },
  {
    id: 33,
    title: "Blueberry Cheesecake",
    size: ['6"', '7"', '8"'],
    description: "Creamy cheesecake topped with blueberry compote.",
    price: ["33.99", "39.99", "42.99"],
    category: "Special Cake",
  },
  {
    id: 34,
    title: "Cartoon Bunny Cake",
    size: ['7"'],
    description: "Adorable bunny-themed cream cake.",
    price: ["55.99"],
    category: "Character Cake",
  },
  {
    id: 35,
    title: "Raspberry Chocolate Cake",
    size: ['6"'],
    description: "Dark chocolate layers with raspberry cream.",
    price: ["35.99"],
    category: "Special Cake",
  },
  {
    id: 36,
    title: "Blueberry Mousse Slice",
    size: ["Single"],
    description: "Light blueberry mousse on soft sponge.",
    price: ["6.49"],
    category: "Slice Cake",
  },
  {
    id: 37,
    title: "Peach Fresh Cream Cake",
    size: ['6"', '8"'],
    description: "Sweet peaches layered with fresh whipped cream.",
    price: ["30.99", "36.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 38,
    title: "Robot Birthday Cake",
    size: ['8"'],
    description: "Robot design cake perfect for kids' birthdays.",
    price: ["54.99"],
    category: "Character Cake",
  },
  {
    id: 39,
    title: "Green Tea Fresh Cream Cake",
    size: ['7"', '8"'],
    description: "Matcha sponge paired with light matcha cream.",
    price: ["31.99", "37.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 40,
    title: "Tiramisu Slice",
    size: ["Single"],
    description: "Coffee-soaked sponge slice with mascarpone cream.",
    price: ["6.49"],
    category: "Slice Cake",
  },
  {
    id: 41,
    title: "Oreo Cream Slice",
    size: ["Single"],
    description: "Vanilla cake slice blended with crushed Oreo cream.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 42,
    title: "Salted Caramel Cake",
    size: ['6"', '7"', '8"'],
    description: "Caramel sponge with salted caramel cream.",
    price: ["36.99", "42.99", "45.99"],
    category: "Special Cake",
  },
  {
    id: 43,
    title: "Chocolate Fresh Cream Cake",
    size: ['6"', '8"'],
    description: "Chocolate sponge with chocolate cream and whipped topping.",
    price: ["30.99", "36.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 44,
    title: "Soccer Ball Cake",
    size: ['7"'],
    description: "Round soccer ball–themed cake.",
    price: ["54.99"],
    category: "Character Cake",
  },
  {
    id: 45,
    title: "Green Tea Mousse Cake",
    size: ['6"'],
    description: "Creamy matcha mousse with soft sponge.",
    price: ["32.99"],
    category: "Mousse Cake",
  },
  {
    id: 46,
    title: "Blueberry Yogurt Cake",
    size: ['6"', '7"'],
    description: "Vanilla sponge filled with blueberry yogurt cream.",
    price: ["29.99", "35.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 47,
    title: "Raspberry Slice Cake",
    size: ["Single"],
    description: "Light sponge slice topped with raspberry cream.",
    price: ["5.99"],
    category: "Slice Cake",
  },
  {
    id: 48,
    title: "Vanilla Mousse Cake",
    size: ['6"', '7"', '8"'],
    description: "Light vanilla mousse paired with classic sponge.",
    price: ["31.99", "35.99", "39.99"],
    category: "Mousse Cake",
  },
  {
    id: 49,
    title: "Custard Cream Cake",
    size: ['7"'],
    description: "Soft sponge filled with sweet house-made custard.",
    price: ["33.99"],
    category: "Fresh Cream Cake",
  },
  {
    id: 50,
    title: "Lemon Cream Slice",
    size: ["Single"],
    description: "Bright lemon sponge slice with smooth lemon cream.",
    price: ["5.49"],
    category: "Slice Cake",
  },
];
