import { Metadata } from "next";
import { EntryType } from "@/lib/mockData";
import ProductList from "../_components/shared/ProductList";
import { cakeCategory } from "@/lib/categoryData";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const data = await fetch(`http://localhost:3000/api/cookies`)
    .then((res) => res.json())
    .then((data) => data.data as EntryType[])
    .catch((err) => console.log(err));

  if (!data) return <div>no data..</div>;

  return (
    <ProductList
      category="cookies"
      data={data}
      asideCategories={cakeCategory}
    />
  );
}

export default page;
