import { Metadata } from "next";
import { EntryType } from "@/lib/mockData";
import { pieCategory } from "@/lib/categoryData";
import ProductList from "../_components/shared/ProductList";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function page({}: Props) {
  const data: EntryType[] = await fetch(
    `http://localhost:3000/api/categories/pies`
  )
    .then((res) => res.json())
    .then((data) => data.data);

  return (
    <ProductList category="pies" data={data} asideCategories={pieCategory} />
  );
}

export default page;
