import { Metadata } from "next";
import { EntryType } from "@/lib/mockData";
import { pieCategory } from "@/lib/categoryData";
import ProductList from "../_components/shared/ProductList";

type Props = {};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function page({}: Props) {
  return <ProductList category="pies" asideCategories={pieCategory} />;
}

export default page;
